version: '3.9'
services:
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - './www:/var/www'
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  nginx:
    container_name: nginx_symfony
    image: nginx:latest
    volumes:
      - './www:/var/www'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - ${SERVER_PORT}:80
    depends_on:
      - database

  database:
    container_name: mysql_symfony
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - './docker/mysql:/var/lib/mysql'